package com.example.service.whatsapp.intelligence

/**
 * Intents classified by the autonomous WhatsApp agent intelligence.
 */
enum class AgentIntent(
    val displayName: String,
    val iconEmoji: String,
    val requiresEscalation: Boolean
) {
    BOOKING_INQUIRY("Booking & Appointments", "📅", false),
    PRICING_REQUEST("Service Pricing & Quotes", "💰", false),
    RESCHEDULE_CANCEL("Reschedule & Cancellation", "🔄", false),
    VIP_CONCIERGE("VIP Concierge Request", "⭐", false),
    COMPLAINT_ESCALATION("Urgent Complaint / Escalation", "🚨", true),
    GENERAL_SALON_QUERY("General Salon Inquiry", "💬", false),
    UNKNOWN("Unclassified Intent", "❓", false)
}

/**
 * Structured decision generated by the autonomous WhatsApp agent intelligence.
 */
data class AgentDecision(
    val intent: AgentIntent,
    val confidence: Float,
    val replyText: String,
    val reasoningTrace: String,
    val suggestedQuickActions: List<String> = emptyList(),
    val requiresHumanEscalation: Boolean = false,
    val isSlotTentativelyLocked: Boolean = false,
    val extractedSlotDetails: String? = null
)
