package com.example.autoreply

import androidx.compose.ui.graphics.Color

/**
 * Stage of the customer conversation inferred from history patterns.
 */
enum class ConversationStage(
    val displayName: String,
    val description: String
) {
    INITIAL_GREETING("Greeting", "Customer first reached out"),
    SERVICE_INQUIRY("Service & Pricing", "Inquiring about hair/beauty services and prices"),
    SCHEDULING("Scheduling Slots", "Discussing dates, times, or availability"),
    DEPOSIT_PENDING("Deposit & Payment", "Ready to pay or awaiting banking verification"),
    CONFIRMED("Booking Confirmed", "Appointment locked in, sending arrival prep"),
    COMPLAINT_ESCALATION("Urgent Support", "Addressing service complaint or delay"),
    AFTERCARE_RETENTION("Aftercare & Retention", "Follow-up, maintenance advice, or rebooking")
}

/**
 * Historical pattern type detected from previous multi-turn interactions.
 */
enum class HistoryPatternType(
    val title: String,
    val defaultEmoji: String,
    val defaultConfidence: Float
) {
    GREETING_NEW_CLIENT("New Client Greeting", "👋", 0.95f),
    SERVICE_PRICING_QUOTE("Personalized Service Quote", "✂️", 0.94f),
    SLOT_TIME_OFFER("Slot Availability Offer", "📅", 0.97f),
    DEPOSIT_BANKING_LOCK("Deposit Instructions", "💳", 0.96f),
    MULTITURN_CONTINUATION("Context Continuity Reply", "🔗", 0.92f),
    URGENT_EMPATHY_DEESCALATION("Urgent Support Call", "🚨", 0.98f),
    REPEAT_CLIENT_WARMTH("Returning VIP Welcome", "👑", 0.95f),
    CONFIRMATION_REMINDER("Booking Confirmation", "✅", 0.96f)
}

/**
 * Auto-reply suggestion candidate generated by the ML pattern engine or Gemini neural model.
 */
data class AutoReplySuggestion(
    val id: String,
    val suggestedText: String,
    val shortLabel: String,
    val confidenceScore: Float, // 0.0f to 1.0f
    val patternType: HistoryPatternType,
    val patternRationale: String,
    val contextTags: List<String> = emptyList(),
    val isAiGenerated: Boolean = true
) {
    val confidencePercentage: Int get() = (confidenceScore * 100).toInt().coerceIn(70, 99)
}

/**
 * Key entity and context variables extracted from conversation history patterns.
 */
data class ExtractedConversationContext(
    val customerName: String? = null,
    val detectedService: String? = null,
    val detectedPriceEstimate: String? = null,
    val detectedDayOrTime: String? = null,
    val currentStage: ConversationStage = ConversationStage.INITIAL_GREETING,
    val isUrgent: Boolean = false,
    val hasUnansweredQuestion: Boolean = false,
    val lastCustomerQuery: String = "",
    val turnCount: Int = 0,
    val keySignalsFound: List<String> = emptyList()
)
