package com.example.ui.viewmodel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.data.local.ChatHistoryRepository
import com.example.data.local.ChatMessage
import com.example.data.local.ZamaDatabase
import com.example.data.remote.GeminiAgentService
import com.example.data.remote.GeminiResponseResult
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * UI State representing the current status of the chat messaging flow.
 */
sealed class MessagingUiState {
    object Idle : MessagingUiState()
    data class Generating(val stage: String = "Zama AI is synthesizing...") : MessagingUiState()
    data class Success(val lastReply: String) : MessagingUiState()
    data class Error(val errorMessage: String, val isApiKeyIssue: Boolean = false) : MessagingUiState()
}

/**
 * Modern ChatViewModel that handles:
 * 1. State management for the messaging flow (active messages, typing indicator, neural trace).
 * 2. Integration with Room Database (persisting customer and AI messages reactively).
 * 3. Communication with the Google Gemini API (gemini-3.5-flash) to power AI agent responses.
 */
class ChatViewModel @JvmOverloads constructor(
    application: Application,
    private val database: ZamaDatabase = ZamaDatabase.getDatabase(application),
    private val geminiService: GeminiAgentService = GeminiAgentService(),
    coroutineScopeOverride: CoroutineScope? = null
) : AndroidViewModel(application) {

    private val activeScope: CoroutineScope = coroutineScopeOverride ?: viewModelScope
    private val chatDao = database.chatLogDao()
    private val repository = ChatHistoryRepository(chatDao)

    /**
     * Reactive stream of all chat messages directly from Room database.
     */
    val messages: StateFlow<List<ChatMessage>> = chatDao.getAllChatMessages()
        .stateIn(
            scope = activeScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    /**
     * High-level messaging UI state (Idle, Generating, Success, Error).
     */
    private val _uiState = MutableStateFlow<MessagingUiState>(MessagingUiState.Idle)
    val uiState: StateFlow<MessagingUiState> = _uiState.asStateFlow()

    /**
     * Boolean indicator for whether the AI agent is actively thinking or typing.
     */
    private val _isAiThinking = MutableStateFlow(false)
    val isAiThinking: StateFlow<Boolean> = _isAiThinking.asStateFlow()

    /**
     * Human-like typing stage description (e.g., Reading message, Checking schedule, Typing reply).
     */
    private val _aiTypingStage = MutableStateFlow("Zama AI is typing...")
    val aiTypingStage: StateFlow<String> = _aiTypingStage.asStateFlow()

    /**
     * Current neural reasoning trace generated by Gemini for inspection in UI.
     */
    private val _latestAiTrace = MutableStateFlow(
        "Intent: AutonomousConcierge (Confidence: 99.8%)\n" +
        "Model: gemini-3.5-flash (Google Gemini API)\n" +
        "Database: Room SQLite Synced\n" +
        "Action: Ready to handle real-time bookings and service inquiries."
    )
    val latestAiTrace: StateFlow<String> = _latestAiTrace.asStateFlow()

    /**
     * Tracks the current text in the chat input field.
     */
    private val _currentInputText = MutableStateFlow("")
    val currentInputText: StateFlow<String> = _currentInputText.asStateFlow()

    init {
        // Seed initial friendly greeting into Room if the database table is empty
        activeScope.launch {
            seedInitialGreetingIfEmpty()
        }
    }

    fun onInputTextChanged(newText: String) {
        _currentInputText.value = newText
    }

    /**
     * Main entry point to send a message (text or transcribed voice).
     * 1. Persists user message in Room database.
     * 2. Sets UI state to Generating.
     * 3. Communicates with the Gemini API (model: gemini-3.5-flash).
     * 4. Persists the generated AI agent reply into Room with its reasoning trace.
     */
    fun sendMessage(
        userText: String,
        isVoiceNote: Boolean = false,
        audioModelUsed: String? = null
    ): kotlinx.coroutines.Job? {
        val trimmedText = userText.trim()
        if (trimmedText.isBlank()) return null

        val timeString = formatCurrentTime()
        val userMessageId = "msg_user_${System.currentTimeMillis()}"

        // Reset input field
        _currentInputText.value = ""

        return activeScope.launch {
            // 1. Insert user message into Room
            val userChatMessage = ChatMessage(
                messageId = userMessageId,
                content = trimmedText,
                isFromUser = true,
                senderRole = "USER",
                timestamp = timeString,
                timestampMillis = System.currentTimeMillis(),
                statusTicks = "✓✓",
                isVoiceNote = isVoiceNote,
                audioModelUsed = audioModelUsed
            )
            chatDao.insertChatMessage(userChatMessage)

            // Also keep legacy repository in sync for analytics dashboard
            repository.saveMessage(
                userChatMessage.toUiModel(),
                sessionId = "default_session"
            )

            // 2. Set thinking & UI state
            _isAiThinking.value = true
            _aiTypingStage.value = "Reading inquiry..."
            _uiState.value = MessagingUiState.Generating("Zama AI is reading inquiry...")

            // 3. Prepare multi-turn context from current message history
            val history = messages.value.takeLast(6).map { Pair(it.content, it.isFromUser) }

            // 4. Request response from Gemini API
            _aiTypingStage.value = "Checking salon schedule & pricing..."
            val result = geminiService.generateAgentReply(trimmedText, history)
            _aiTypingStage.value = "Zama AI is typing..."

            when (result) {
                is GeminiResponseResult.Success -> {
                    val aiMessageId = "msg_ai_${System.currentTimeMillis()}"
                    val aiChatMessage = ChatMessage(
                        messageId = aiMessageId,
                        content = result.replyText,
                        isFromUser = false,
                        senderRole = "AI",
                        timestamp = formatCurrentTime(),
                        timestampMillis = System.currentTimeMillis(),
                        statusTicks = "✓✓",
                        aiTrace = result.reasoningTrace
                    )

                    // 5. Persist AI response in Room
                    chatDao.insertChatMessage(aiChatMessage)
                    repository.saveMessage(
                        aiChatMessage.toUiModel(),
                        sessionId = "default_session",
                        aiTrace = result.reasoningTrace
                    )

                    _latestAiTrace.value = result.reasoningTrace
                    _isAiThinking.value = false
                    _uiState.value = MessagingUiState.Success(result.replyText)
                }

                is GeminiResponseResult.Error -> {
                    val fallbackText = result.fallbackReply ?: "I encountered an error connecting to our autonomous servers. Please try again."
                    val aiMessageId = "msg_ai_${System.currentTimeMillis()}"
                    val aiChatMessage = ChatMessage(
                        messageId = aiMessageId,
                        content = fallbackText,
                        isFromUser = false,
                        senderRole = "AI",
                        timestamp = formatCurrentTime(),
                        timestampMillis = System.currentTimeMillis(),
                        statusTicks = "✓✓",
                        aiTrace = "Error: ${result.message}"
                    )
                    chatDao.insertChatMessage(aiChatMessage)

                    _latestAiTrace.value = "Error: ${result.message}\nAction: Fallback dispatched."
                    _isAiThinking.value = false
                    _uiState.value = MessagingUiState.Error(result.message, result.isApiKeyIssue)
                }
            }
        }
    }

    /**
     * Resets all chat messages from Room and restores the initial greeting.
     */
    fun clearChatHistory(): kotlinx.coroutines.Job {
        return activeScope.launch {
            chatDao.clearAllChatMessages()
            repository.clearHistory()
            seedInitialGreetingIfEmpty()
            _uiState.value = MessagingUiState.Idle
        }
    }

    /**
     * Seeds initial greeting message if Room is empty.
     */
    private suspend fun seedInitialGreetingIfEmpty() {
        val currentList = chatDao.getAllChatMessages().first()
        if (currentList.isEmpty()) {
            val seedUser = ChatMessage(
                messageId = "seed_user_01",
                content = "Hi, how much for braids and do you have Saturday at 2pm?",
                isFromUser = true,
                senderRole = "USER",
                timestamp = "14:02",
                timestampMillis = System.currentTimeMillis() - 120_000
            )
            val seedAi = ChatMessage(
                messageId = "seed_ai_01",
                content = "Hi Sarah 👋 Knotless Braids start from R650. We have Saturday at 2:00 PM open with our senior stylist! Shall I confirm this reservation for you?",
                isFromUser = false,
                senderRole = "AI",
                timestamp = "14:02",
                timestampMillis = System.currentTimeMillis() - 60_000,
                aiTrace = "Intent: PricingInquiry + BookingRequest (Confidence: 99.4%)\n" +
                        "Model: gemini-3.5-flash (Google Gemini API)\n" +
                        "Action: Slot #BK-749 tentative lock on calendar."
            )
            chatDao.insertChatMessages(listOf(seedUser, seedAi))
        }
    }

    private fun formatCurrentTime(): String {
        val sdf = SimpleDateFormat("HH:mm", Locale.getDefault())
        return sdf.format(Date())
    }

    /**
     * ViewModelFactory for ChatViewModel providing Room database and GeminiAgentService dependencies.
     */
    class Factory(
        private val application: Application,
        private val geminiService: GeminiAgentService = GeminiAgentService()
    ) : ViewModelProvider.Factory {
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel> create(modelClass: Class<T>): T {
            if (modelClass.isAssignableFrom(ChatViewModel::class.java)) {
                val database = ZamaDatabase.getDatabase(application)
                return ChatViewModel(application, database, geminiService) as T
            }
            throw IllegalArgumentException("Unknown ViewModel class: ${modelClass.name}")
        }
    }
}
